version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: guessright-mongodb
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=guessright
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    networks:
      - guessright-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: guessright-app
    restart: always
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/guessright
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - guessright-network

networks:
  guessright-network:
    driver: bridge

volumes:
  mongodb-data: