version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: guessright-mongodb
    restart: always
    ports:
      - 27018:27017
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=guessright

volumes:
  mongodb-data: